### ISSUE TITLE
password-store-menu asking password every time

### ISSUE THREAD

**Issue by muralikodali** [rjekker/password-store-menu#1]
every time i try to use password-store-menu to view or copy pass word, it is asking for gpg password. where as in case of password-store program, it is not asking for password to copy password to clipboard or something else.

is there any way to stop it asking for password each and every time.

**Comment by rjekker** [comment]
I wonder if this is a problem with password-store-menu. It might be that emacs is not properly using the gpg client session.

If you do M-x password-store-copy, and try to copy a password, does it also ask for a password?

**Comment by rjekker** [comment]
Another thing to check: you should have the following in your shell init file (e.g. .bashrc or .zshenv):

``` sh
export GPG_TTY=$(tty)
```

and you might try the exec-path-from-shell package to copy this into your emacs session:

``` elisp
(require 'exec-path-from-shell)
(exec-path-from-shell-initialize)
```

**Comment by muralikodali** [comment]
thanks for pointing to shell init configuration.

in fish shell, it should be ```set -gx GPG_TTY (tty)```. After changing the export setting, password-store-menu is working fine.

**Comment by muralikodali** [comment]
thanks for pointing to shell init configuration.

in fish shell, it should be ```set -gx GPG_TTY (tty)```. After changing the export setting, password-store-menu is working fine.
